version: '3.6'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    environment:
      - DB_URL=postgres
    command: ./mvnw -Dmaven.repo.local=./.m2 jetty:run

  postgres:
    image: postgres:13.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql
volumes:
  postgres:
